name = "create"
author = "rennto"
version = "1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b20725df74dbfd9d9fa11243e4127a2c4744c5eb7e90bad973f92deea96beb44"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
